# Generated by Django 5.1 on 2024-09-24 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="people_list",
            new_name="tagged_users",
        ),
    ]
