# Generated by Django 5.0.7 on 2024-08-02 02:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_friend"),
        ("api", "0002_invitationlink_status"),
    ]

    operations = []
