# Generated by Django 5.1 on 2024-09-12 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_friend_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friend",
            unique_together={("to_user", "from_user", "status")},
        ),
    ]
