# Generated by Django 5.0.7 on 2024-08-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_major_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationlink',
            name='invitee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
