# Generated by Django 5.1 on 2024-09-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_people_list_project_tagged_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contact",
            field=models.TextField(blank=True, null=True),
        ),
    ]
