# Generated by Django 5.0.7 on 2024-07-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_invitationlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationlink",
            name="invitee_name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
