# Generated by Django 5.0.7 on 2024-07-24 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="email",
            new_name="username",
        ),
    ]
