# Generated by Django 5.0.7 on 2024-07-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_invitationlink_invitee_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationlink",
            name="invitee_name",
            field=models.CharField(max_length=255),
        ),
    ]
