# Generated by Django 5.1 on 2024-09-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_friend_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
