# Generated by Django 4.2.14 on 2024-08-09 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_introduction_profile_one_degree_count_tool_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='description',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='portfoliolink',
            old_name='url',
            new_name='portfolioLink',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='name',
            new_name='tool',
        ),
    ]
