# Generated by Django 5.0.7 on 2024-07-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rename_email_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
