# Generated by Django 4.2.14 on 2024-08-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_description_experience_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
