# Generated by Django 5.1 on 2024-09-24 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_people_list_project_tagged_users"),
        ("api", "0006_like"),
    ]

    operations = []
